export enum BillingStatus {
    NotBilledNonExport = 0,
    BillPendingNonExport = 1,
    BillInvoicePendingNonExport = 2,
    BillingSuccessfulNonExport = 3,
    NotBilledExportEligible = 10,
    BillPendingExportEligible = 11,
    BillInvoicePendingExportEligible = 12,
    BillingSucessfulExportPending = 13,
    ExportProcessing = 14,
    ExportSuccessful = 15,
    ExportReset = 16,
    InvalidTransactionId = 17,
    ExportTimeout = 18,
    BillingExportError = 90,
    BillingError = 91,
    InvoiceError = 92,
    XactwareError = 93,
    XactimateError = 94,
}
