export enum OrderSubStatus {
    Customer = 1,
    UnderReview = 5,
    ProcessStarted = 6,
    SiteMap = 7,
    NeedToId = 8,
    Duplicate = 9,
    CanceledByClient = 10,
    PoorImages = 11,
    NoId = 12,
    ReportTypeChange = 14,
    NoImages = 15,
    Other = 16,
    System = 17,
    CardRejected = 18,
    Sent = 19,
    Sent1 = 20,
    CustomerResponse = 21,
    WrongHouse = 24,
    ReadyToSend = 26,
    CreditcardFailure = 27,
    Addressverified = 29
}
